# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "testes" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tir:
      name: teste
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: Checkout private tools
          uses: actions/checkout@v4
          with:
            repository: engpro/protheus-ci-universo-artefatos
            token: ${{ secrets.GH_ARTE_SECRET }} # `GH_PAT` is a secret that contains your PAT
            path: artefatos
            ref: master
            github-server-url: "https://code.engpro.totvs.com.br"
        - name: limits
          run: |
            sudo sysctl -w fs.file-max=32768
            sysctl fs.file-max
        - name: list
          run: |
            ls -lah ${{ github.workspace }}/artefatos
        - name: docker
          run: |
            docker run --rm alpine echo foi
